# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '137Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 137Project
    pod 'Firebase/Core'
    pod 'Firebase/Auth'

  target '137ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '137ProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
